# Generated by Django 4.2.7 on 2023-11-03 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('admission_number', models.CharField(max_length=10)),
                ('child_first_name', models.CharField(max_length=150)),
                ('child_last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('fathers_name', models.CharField(max_length=200)),
                ('fathers_contact_number', models.IntegerField(max_length=10)),
                ('fathers_whatsapp_number', models.IntegerField(max_length=10)),
                ('mothers_name', models.CharField(max_length=200)),
                ('mothers_contact_number', models.IntegerField(max_length=10)),
                ('mothers_whatsapp_number', models.IntegerField(max_length=10)),
                ('resident_contact_number', models.IntegerField(max_length=10)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(max_length=200)),
                ('address_line3', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('is_polymath_student', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HolidayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('holiday_code', models.CharField(max_length=10)),
                ('holiday_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('package_type_code', models.CharField(max_length=10)),
                ('package_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('package_code', models.CharField(max_length=10)),
                ('package_name', models.CharField(max_length=200)),
                ('hours_per_day', models.IntegerField()),
                ('no_of_days', models.IntegerField()),
                ('days_per_month', models.ImageField(upload_to='')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('holiday_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.holidaytype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
