# Generated by Django 5.0.1 on 2024-09-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childenrollment',
            name='flex_package',
        ),
        migrations.RemoveField(
            model_name='childenrollment',
            name='holiday_package',
        ),
        migrations.RemoveField(
            model_name='childenrollment',
            name='normal_package',
        ),
        migrations.CreateModel(
            name='ChildPackageMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('flex_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flex_package', to='core.flexpackages')),
                ('holiday_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_package', to='core.fixedpackage')),
                ('normal_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_package', to='core.fixedpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
