# Generated by Django 5.0.1 on 2025-06-14 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('pdf_filename', models.CharField(max_length=255)),
                ('pdf_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.childenrollment')),
            ],
            options={
                'verbose_name': 'Enrollment Form',
                'verbose_name_plural': 'Enrollment Forms',
                'db_table': 'dc_enrollment_forms',
            },
        ),
        migrations.CreateModel(
            name='InvoiceMemo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('memo_date', models.DateField()),
                ('memo_code', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('previous_month_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_month_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_month_payment_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('package_name', models.CharField(max_length=200)),
                ('package_base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_attended', models.IntegerField(default=0)),
                ('expected_days', models.IntegerField(default=22)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_half_charge_applied', models.BooleanField(default=False)),
                ('current_month_package_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hours_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('holiday_attendance_days', models.IntegerField(default=0)),
                ('holiday_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_month_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_month_payment_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent to Parent')], default='GENERATED', max_length=20)),
                ('branch_name', models.CharField(max_length=200)),
                ('center_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'Invoice Memo',
                'verbose_name_plural': 'Invoice Memos',
                'db_table': 'dc_invoice_memos',
                'ordering': ['-year', '-month', '-memo_date'],
                'unique_together': {('child', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MemoPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoicememo')),
            ],
            options={
                'verbose_name': 'Memo Payment',
                'verbose_name_plural': 'Memo Payments',
                'db_table': 'dc_memo_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
