# Generated by Django 5.0.1 on 2025-02-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='day_care',
        ),
    ]
