# Generated by Django 5.0.1 on 2024-07-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrachargeshistory',
            name='extra_charges_after530',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.extrahoursafter530'),
        ),
        migrations.AlterField(
            model_name='extrachargeshistory',
            name='extra_charges_before530',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.extrahoursupto530'),
        ),
    ]
