# Generated by Django 5.0.1 on 2025-06-13 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('pdf_filename', models.CharField(max_length=255)),
                ('pdf_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.childenrollment')),
            ],
            options={
                'verbose_name': 'Enrollment Form',
                'verbose_name_plural': 'Enrollment Forms',
                'db_table': 'dc_enrollment_forms',
            },
        ),
    ]
