# Generated by Django 4.2.7 on 2023-11-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_hours_standard_rate_first_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_hours_standard_rate_Second_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_hours_standard_rate_third_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_hours_standard_rate_fourth_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_hours_standard_rate_fifth_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_hours_standard_rate_sixth_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_hours_standard_rate_seventh_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_hours_standard_rate_eighth_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_hours_standard_rate_nineth_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_hours_standard_rate_tenth_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_name', models.CharField(max_length=550)),
                ('standard_hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_precentage_for_Unutilized_packages', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BaseRates',
        ),
        migrations.AddField(
            model_name='additionalcharges',
            name='base_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rates'),
        ),
    ]
