# Generated by Django 5.0 on 2023-12-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='discount_precentage_for_Unutilized_packages',
            new_name='no_days_months',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='rate',
            new_name='no_hours',
        ),
        migrations.AddField(
            model_name='package',
            name='base_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='is_holiday_package',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='no_days_week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='from_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='to_time',
            field=models.TimeField(),
        ),
    ]
