# Generated by Django 5.0.1 on 2024-07-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_extrachargeshistory_extra_charges_after530_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrahoursupto530',
            old_name='rate',
            new_name='extra_rate',
        ),
    ]
