# Generated by Django 5.0.1 on 2025-06-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enrollmentform_invoicememo_memopayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicememo',
            old_name='subtotal',
            new_name='month_net_balance',
        ),
        migrations.RenameField(
            model_name='invoicememo',
            old_name='total_amount',
            new_name='month_total_charge',
        ),
        migrations.RenameField(
            model_name='invoicememo',
            old_name='current_month_payment_amount',
            new_name='total_payments_received',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='current_month_payment_receipt',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='previous_month_outstanding',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='previous_month_payment_amount',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='previous_month_payment_receipt',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='remaining_balance',
        ),
        migrations.AddField(
            model_name='invoicememo',
            name='payment_receipts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicememo',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent to Parent'), ('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('CREDIT', 'Has Credit Balance')], default='GENERATED', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoicememo')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'dc_payment_transactions',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.DeleteModel(
            name='MemoPayment',
        ),
    ]
