# Generated by Django 4.2.7 on 2023-11-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rates_effective_from_rates_effective_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='effective_to',
            field=models.DateField(null=True),
        ),
    ]
