# Generated by Django 4.2.7 on 2023-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_discount_precentage_for_unutilized_packages_package_no_days_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
