# Generated by Django 5.0.1 on 2024-09-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_childenrollment_flex_package_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageChangerequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("user_created", models.CharField(max_length=50)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("user_updated", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("date_requested", models.DateField(auto_now_add=True)),
                ("date_approved", models.DateField(null=True)),
                ("reason_for_request", models.TextField()),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.child"
                    ),
                ),
                (
                    "new_fixed_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_new_fixed_package",
                        to="core.fixedpackage",
                    ),
                ),
                (
                    "new_flexed_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_new_flex_package",
                        to="core.flexpackages",
                    ),
                ),
                (
                    "old_fixed_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_old_fixed_package",
                        to="core.fixedpackage",
                    ),
                ),
                (
                    "old_flexed_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_old_flex_package",
                        to="core.flexpackages",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Change Request",
                "verbose_name_plural": "Package Change Requests",
                "db_table": "dc_package_change_request",
            },
        ),
    ]
