# Generated by Django 5.0.1 on 2025-06-17 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_subtotal_invoicememo_month_net_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicememo',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount to pay (all 3 months combined)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicememo',
            name='total_outstanding',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total outstanding from previous months', max_digits=10),
        ),
        migrations.CreateModel(
            name='InvoiceMemoDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('month_sequence', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month_name', models.CharField(max_length=20)),
                ('month_type', models.CharField(choices=[('OUTSTANDING', 'Outstanding/Credits from Previous Month'), ('CALCULATED', 'Calculated with Attendance'), ('ADVANCE', 'Advance Payment (Full Package)')], max_length=20)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calculation_details', models.JSONField(default=dict)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.invoicememo')),
            ],
            options={
                'verbose_name': 'Invoice Memo Detail',
                'verbose_name_plural': 'Invoice Memo Details',
                'db_table': 'dc_invoice_memo_details',
                'ordering': ['memo', 'month_sequence'],
                'unique_together': {('memo', 'month_sequence')},
            },
        ),
    ]
