# Generated by Django 5.0 on 2023-12-26 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_branch_contact_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_code', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
            ],
            options={
                'verbose_name': 'Child Assignment',
                'verbose_name_plural': 'Child Assignments',
            },
        ),
        migrations.CreateModel(
            name='DayCare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('daycare_code', models.CharField(max_length=10)),
                ('daycare_name', models.CharField(max_length=150)),
                ('daycare_incharge', models.CharField(max_length=150)),
                ('daycare_contact_number', models.CharField(max_length=15)),
                ('daycare_contact_mobile_number', models.CharField(max_length=15)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.DeleteModel(
            name='ChildAssignment',
        ),
    ]
