# Generated by Django 4.2.7 on 2023-11-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rates_effective_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcharges',
            name='rate',
        ),
        migrations.AddField(
            model_name='additionalcharges',
            name='additional_rate_name',
            field=models.CharField(default='aaa', max_length=550),
            preserve_default=False,
        ),
    ]
