# Generated by Django 5.0.1 on 2024-07-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_rate_extrahoursupto530_extra_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrahoursupto530',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='extrahoursupto530',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='extrahoursupto530',
            name='to_time',
        ),
        migrations.AddField(
            model_name='extrahoursupto530',
            name='hour_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrahoursupto530',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrahoursupto530',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrahoursupto530',
            name='extra_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
