# Generated by Django 5.0.1 on 2024-09-05 05:58

from django.db import migrations


class Migration(migrations.Migration):
    operations = [
        migrations.AlterModelOptions(
            name="childpackagemapping",
            options={
                "verbose_name": "Child Package Mapping",
                "verbose_name_plural": "Child Package Mappings",
            },
        ),
        migrations.AlterModelTable(
            name="childpackagemapping",
            table="dc_child_package_mapping",
        ),
    ]
