# Generated by Django 5.0.1 on 2025-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoicememo_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicememodetail',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
