# Generated by Django 5.0.1 on 2024-09-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_childpackagemapping_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childpackagemapping',
            name='is_holiday_package',
            field=models.BooleanField(default=False),
        ),
    ]
