# Generated by Django 5.0 on 2023-12-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_childenrollment_daycare_delete_childassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_name', models.CharField(max_length=250)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='childenrollment',
            name='package',
        ),
        migrations.AddField(
            model_name='childenrollment',
            name='holiday_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_package', to='core.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childenrollment',
            name='normal_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='normal_package', to='core.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childenrollment',
            name='discount_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.discounts'),
            preserve_default=False,
        ),
    ]
