# Generated by Django 5.0.1 on 2024-08-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_extrahoursupto530_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrachargeshistory',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrachargeshistory',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
