# Generated by Django 4.2.7 on 2023-11-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_additionalcharges_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcharges',
            name='map_column',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
