# Generated by Django 5.0 on 2023-12-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_discounts_remove_childenrollment_package_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='Discount',
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'discount', 'verbose_name_plural': 'discounts'},
        ),
    ]
