# Generated by Django 4.2.7 on 2023-11-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_additionalcharges_map_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalcharges',
            old_name='extra_hours_standard_rate_Second_hour',
            new_name='Slot_number_hour',
        ),
        migrations.RenameField(
            model_name='additionalcharges',
            old_name='extra_hours_standard_rate_eighth_hour',
            new_name='extra_rate',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='additional_rate_name',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='extra_hours_standard_rate_fifth_hour',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='extra_hours_standard_rate_first_hour',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='extra_hours_standard_rate_fourth_hour',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='extra_hours_standard_rate_nineth_hour',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='extra_hours_standard_rate_seventh_hour',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='extra_hours_standard_rate_sixth_hour',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='extra_hours_standard_rate_tenth_hour',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='extra_hours_standard_rate_third_hour',
        ),
        migrations.RemoveField(
            model_name='additionalcharges',
            name='map_column',
        ),
        migrations.AddField(
            model_name='additionalcharges',
            name='base_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rates'),
            preserve_default=False,
        ),
    ]
