# Generated by Django 5.0.1 on 2025-06-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoicememodetail_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='childpackagemapping',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Discount applied to this package mapping', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.discount'),
        ),
    ]
