# Generated by Django 5.0.1 on 2024-09-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_childpackagemapping_is_holiday_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagechangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Pending Approval', max_length=30),
        ),
    ]
