# Generated by Django 5.0.1 on 2024-08-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_extrachargeshistory_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageextrahoursmapping',
            name='extra_hours_after_530',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.extrahoursafter530'),
        ),
        migrations.AlterField(
            model_name='packageextrahoursmapping',
            name='extra_hours_upto_530',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.extrahoursupto530'),
        ),
    ]
