# Generated by Django 5.0.1 on 2024-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_packagechangerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpackage',
            name='is_holiday_package',
            field=models.BooleanField(default=False),
        ),
    ]
