# Generated by Django 5.0 on 2023-12-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_discounts_discount_alter_discount_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childenrollment',
            old_name='discount_rate',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='childenrollment',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('Submitted', 'Submitted')], default='Pending Approval', max_length=30),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
