# Generated by Django 5.0.1 on 2025-06-30 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_childpackagemapping_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicememo',
            options={'ordering': ['-memo_year', '-memo_month', '-memo_date'], 'verbose_name': 'Invoice Memo', 'verbose_name_plural': 'Invoice Memos'},
        ),
        migrations.AlterModelOptions(
            name='invoicememodetail',
            options={'ordering': ['memo', 'month_sequence'], 'verbose_name': 'Invoice Month Detail', 'verbose_name_plural': 'Invoice Month Details'},
        ),
        migrations.RenameField(
            model_name='invoicememo',
            old_name='month',
            new_name='memo_month',
        ),
        migrations.RenameField(
            model_name='invoicememo',
            old_name='year',
            new_name='memo_year',
        ),
        migrations.RenameField(
            model_name='invoicememodetail',
            old_name='month',
            new_name='actual_month',
        ),
        migrations.RenameField(
            model_name='invoicememodetail',
            old_name='year',
            new_name='actual_year',
        ),
        migrations.RenameField(
            model_name='invoicememodetail',
            old_name='balance_amount',
            new_name='discount_applied',
        ),
        migrations.RenameField(
            model_name='invoicememodetail',
            old_name='charge_amount',
            new_name='extra_hours_charge',
        ),
        migrations.RenameField(
            model_name='invoicememodetail',
            old_name='payment_amount',
            new_name='gross_charges',
        ),
        migrations.AlterUniqueTogether(
            name='invoicememo',
            unique_together={('child', 'memo_year', 'memo_month')},
        ),
        migrations.RemoveField(
            model_name='invoicememodetail',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='invoicememo',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total of all charges before payments', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicememo',
            name='net_amount_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount to pay (gross_total - total_payments)', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicememo',
            name='total_current_month',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current month net amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicememo',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total payments across all months', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicememo',
            name='total_previous_month',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Previous month net amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='days_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='expected_days',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='holiday_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='is_half_charge_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='net_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='package_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='package_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='payment_receipts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='payments_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicememodetail',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicememo',
            name='total_outstanding',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Outstanding from 2 months ago', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicememodetail',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_details', to='core.invoicememo'),
        ),
        migrations.AlterField(
            model_name='invoicememodetail',
            name='month_type',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding (2 months ago)'), ('PREVIOUS', 'Previous month'), ('CURRENT', 'Current month')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='invoicememo',
            table='dc_invoice_memos_v2',
        ),
        migrations.AlterModelTable(
            name='invoicememodetail',
            table='dc_invoice_memo_details_v2',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='attendance_percentage',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='current_month_package_fee',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='days_attended',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='discount_applied',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='expected_days',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='extra_hours_charge',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='holiday_attendance_days',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='holiday_charge',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='is_half_charge_applied',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='month_net_balance',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='month_total_charge',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='package_base_fee',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='payment_receipts',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='total_payments_received',
        ),
    ]
