# Generated by Django 5.0.1 on 2024-08-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_packageextrahoursmapping_extra_hours_after_530_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageextrahoursmapping',
            name='extra_hours_after_530',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraHoursAfter530', to='core.extrahoursafter530'),
        ),
        migrations.AlterField(
            model_name='packageextrahoursmapping',
            name='extra_hours_upto_530',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraHoursUpto530', to='core.extrahoursupto530'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_date', models.DateField()),
                ('invoice_no', models.CharField(blank=True, null=True)),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('receipt_no', models.CharField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'Invoices',
                'verbose_name_plural': 'Invoices',
                'db_table': 'dc_invoices',
            },
        ),
    ]
