# Generated by Django 4.2.7 on 2023-12-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_extra_hours_standard_rate_second_hour_additionalcharges_slot_number_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharges',
            name='Slot_number_hour',
            field=models.IntegerField(),
        ),
    ]
