# Generated by Django 5.0.1 on 2025-06-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_invoicememo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicememo',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='invoicememo',
            name='center_name',
        ),
    ]
