# Generated by Django 5.0.1 on 2024-08-16 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_packageextrahoursmapping_extra_hours_after_530_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='day_care',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
            preserve_default=False,
        ),
    ]
