# Generated by Django 5.0.1 on 2024-09-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fixedpackage_is_holiday_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagechangerequest',
            name='new_holiday_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_new_holiday_package', to='core.flexpackages'),
        ),
    ]
