# Generated by Django 4.2.7 on 2023-12-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_additionalcharges_slot_number_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalcharges',
            old_name='Slot_number_hour',
            new_name='slot_number_hour',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='standard_hourly_rate',
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('standard_hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(null=True)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rates')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
