# Generated by Django 5.0 on 2023-12-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_discount_rate_childenrollment_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childenrollment',
            options={'verbose_name': 'enrollment', 'verbose_name_plural': 'enrollments'},
        ),
    ]
