# Generated by Django 4.2.7 on 2023-12-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_slot_number_hour_additionalcharges_slot_number_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('extra_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(null=True)),
                ('base_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rates')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AdditionalCharges',
        ),
    ]
