# Generated by Django 5.0.1 on 2024-08-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attendancelog_branch_attendancelog_day_care'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTerm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('package_type_code', models.CharField(max_length=10)),
                ('package_type_name', models.CharField(max_length=100)),
                ('is_fixed_package', models.BooleanField(default=True)),
                ('is_dynamic_package', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Package Term',
                'verbose_name_plural': 'Package Terms',
                'db_table': 'dc_package_terms',
            },
        ),
    ]
