# Generated by Django 5.0 on 2023-12-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_childenrollment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('Submitted', 'Submitted')], default='Pending Approval', max_length=30),
        ),
    ]
