# Generated by Django 5.0.1 on 2025-06-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_invoicememo_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoicememo',
            table='dc_invoice_memos',
        ),
        migrations.AlterModelTable(
            name='invoicememodetail',
            table='dc_invoice_memo_details',
        ),
    ]
