# Generated by Django 5.2.3 on 2025-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_invoicememo_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user_created',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user_updated',
            field=models.CharField(default='system', max_length=50),
        ),
    ]
