# Generated by Django 5.0 on 2024-01-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_discount_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='recipt_number',
        ),
        migrations.AddField(
            model_name='childenrollment',
            name='recipt_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Pending Approval', max_length=30),
        ),
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Pending Approval', max_length=30),
        ),
    ]
