# Generated by Django 5.0.1 on 2024-09-16 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_packagechangerequest_old_holiday_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagechangerequest',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='packagechangerequest',
            name='new_holiday_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_new_holiday_package', to='core.fixedpackage'),
        ),
        migrations.AlterField(
            model_name='packagechangerequest',
            name='old_holiday_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_old_holiday_package', to='core.fixedpackage'),
        ),
    ]
