# Generated by Django 5.0.1 on 2024-08-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_package_package_term'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='FixedPackage',
        ),
        migrations.AlterModelOptions(
            name='fixedpackage',
            options={'verbose_name': 'fixed package', 'verbose_name_plural': 'fixed packages'},
        ),
        migrations.AlterModelTable(
            name='fixedpackage',
            table='dc_fixed_packages',
        ),
    ]
