# Generated by Django 5.0.1 on 2024-11-04 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_packagechangerequest_effective_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterChangerequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('date_approved', models.DateField(null=True)),
                ('reason_for_request', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Pending Approval', max_length=30)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('new_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_new_branch', to='core.branch')),
                ('new_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_new_center', to='core.daycare')),
                ('old_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_old_branch', to='core.branch')),
                ('old_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_old_center', to='core.daycare')),
            ],
            options={
                'verbose_name': 'Center Change Request',
                'verbose_name_plural': 'Center Change Requests',
                'db_table': 'dc_center_change_request',
            },
        ),
    ]
