# Generated by Django 5.0 on 2024-01-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_child_recipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='enrollement_approved',
            field=models.BooleanField(default=False),
        ),
    ]
