# Generated by Django 5.0.1 on 2025-12-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_attendance_removal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='is_vacation_package',
            field=models.BooleanField(default=False),
        ),
    ]
