# Generated by Django 5.0.1 on 2024-08-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_package_fixedpackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedpackage',
            name='package_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.packageterm'),
        ),
    ]
