# Generated by Django 4.2.7 on 2024-01-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_child_enrollement_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childenrollment',
            name='discount',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.discount'),
        ),
    ]
