# Generated by Django 5.0.1 on 2025-12-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_is_vacation_package_to_packagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='childpackagemapping',
            name='vacation_package',
            field=models.ForeignKey(blank=True, help_text='Package for polymath/other holidays (vacation package type)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacation_package', to='core.fixedpackage'),
        ),
    ]
