# Generated by Django 5.0.1 on 2024-08-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_fixedpackage_package_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPackages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('package_code', models.CharField(max_length=10)),
                ('package_name', models.CharField(max_length=200)),
                ('no_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_days_week', models.IntegerField()),
                ('no_days_months', models.IntegerField()),
                ('package_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('package_term', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.packageterm')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype')),
            ],
            options={
                'verbose_name': 'flex package',
                'verbose_name_plural': 'flex packages',
                'db_table': 'dc_flex_packages',
            },
        ),
    ]
