# Generated by Django 5.0.1 on 2025-12-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_vacation_package_to_childpackagemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagechangerequest',
            name='old_vacation_package',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_old_vacation_package',
                to='core.fixedpackage'
            ),
        ),
        migrations.AddField(
            model_name='packagechangerequest',
            name='new_vacation_package',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_new_vacation_package',
                to='core.fixedpackage'
            ),
        ),
    ]
