# Generated by Django 4.2.7 on 2024-01-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_childenrollment_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
