# Generated by Django 5.0.1 on 2024-08-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_flexpackages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageextrahoursmapping',
            name='package',
        ),
        migrations.AddField(
            model_name='packageextrahoursmapping',
            name='fixed_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fixedpackage'),
        ),
        migrations.AddField(
            model_name='packageextrahoursmapping',
            name='flex_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.flexpackages'),
        ),
    ]
