# Generated by Django 5.0.1 on 2024-01-31 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_child_is_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_logged', models.DateField()),
                ('time_logged', models.TimeField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
            },
        ),
    ]
