# Generated by Django 5.0.1 on 2026-01-02 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_vacation_package_to_packagechangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLogAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('old_date_logged', models.DateField(help_text='Original date logged before edit')),
                ('old_time_logged', models.TimeField(help_text='Original time logged before edit')),
                ('new_date_logged', models.DateField(help_text='New date logged after edit')),
                ('new_time_logged', models.TimeField(help_text='New time logged after edit')),
                ('edited_by', models.CharField(help_text='Username of the person who made the change', max_length=50)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the change was made')),
                ('edit_reason', models.TextField(blank=True, help_text='Optional reason for the edit', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the editor', null=True)),
                ('attendance_log', models.ForeignKey(help_text='The attendance log record that was edited', on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='core.attendancelog')),
                ('child', models.ForeignKey(help_text='Child reference for easier querying', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_audits', to='core.child')),
            ],
            options={
                'verbose_name': 'Attendance Log Audit',
                'verbose_name_plural': 'Attendance Log Audits',
                'db_table': 'dc_attendance_log_audit',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['child', 'edited_at'], name='dc_attendan_child_i_289a1f_idx'), models.Index(fields=['attendance_log', 'edited_at'], name='dc_attendan_attenda_cd3294_idx'), models.Index(fields=['edited_by', 'edited_at'], name='dc_attendan_edited__795ec5_idx')],
            },
        ),
    ]
