# Generated by Django 5.0.1 on 2024-08-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_packageextrahoursmapping_package_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packageextrahoursmapping',
            table='dc_package_extra_charges_mapping',
        ),
    ]
