# Generated by Django 5.0.1 on 2024-01-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attendancelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='daycare',
            new_name='center',
        ),
    ]
