# Generated by Django 5.0.1 on 2026-01-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_attendance_log_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAdjustmentRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('request_date', models.DateField(help_text='Date for which attendance is being requested')),
                ('in_time', models.TimeField(blank=True, help_text='Requested check-in time', null=True)),
                ('out_time', models.TimeField(blank=True, help_text='Requested check-out time', null=True)),
                ('entry_type', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out'), ('BOTH', 'Both In and Out')], help_text='Type of time entry being requested', max_length=10)),
                ('reason', models.TextField(help_text='Reason for the time adjustment request')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20)),
                ('requested_by', models.CharField(help_text='Username of the person who submitted the request', max_length=50)),
                ('requested_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was submitted')),
                ('approved_by', models.CharField(blank=True, help_text='Username of the person who approved/rejected the request', max_length=50, null=True)),
                ('approved_date', models.DateTimeField(blank=True, help_text='Timestamp when the request was approved/rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if the request was rejected', null=True)),
                ('child', models.ForeignKey(help_text='Child for whom the time adjustment is requested', on_delete=django.db.models.deletion.CASCADE, related_name='time_adjustment_requests', to='core.child')),
                ('in_attendance_log', models.ForeignKey(blank=True, help_text='Attendance log created for check-in upon approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_adjustment_in_requests', to='core.attendancelog')),
                ('out_attendance_log', models.ForeignKey(blank=True, help_text='Attendance log created for check-out upon approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_adjustment_out_requests', to='core.attendancelog')),
            ],
            options={
                'verbose_name': 'Time Adjustment Request',
                'verbose_name_plural': 'Time Adjustment Requests',
                'db_table': 'dc_time_adjustment_request',
                'ordering': ['-requested_date'],
                'indexes': [models.Index(fields=['child', 'request_date'], name='dc_time_adj_child_i_330340_idx'), models.Index(fields=['status', 'requested_date'], name='dc_time_adj_status_db1663_idx')],
            },
        ),
    ]
