# Generated by Django 5.0.1 on 2024-08-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_packageextrahoursmapping_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='childenrollment',
            name='flex_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flex_package', to='core.flexpackages'),
        ),
        migrations.AlterField(
            model_name='childenrollment',
            name='holiday_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_package', to='core.fixedpackage'),
        ),
        migrations.AlterField(
            model_name='childenrollment',
            name='normal_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_package', to='core.fixedpackage'),
        ),
    ]
