# Generated by Django 4.2.15 on 2024-08-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_childenrollment_flex_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaytype',
            name='is_other_school_holiday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaytype',
            name='is_polymath_holiday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaytype',
            name='is_public_holiday',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
