# Generated by Django 5.0.1 on 2026-01-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_time_adjustment_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentDiscountRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(help_text='Date from which the discount should start applying')),
                ('reason', models.TextField(help_text='Reason for requesting the discount')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20)),
                ('requested_by', models.CharField(help_text='Username of the person who submitted the request', max_length=50)),
                ('requested_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was submitted')),
                ('approved_by', models.CharField(blank=True, help_text='Username of the person who approved/rejected the request', max_length=50, null=True)),
                ('approved_date', models.DateTimeField(blank=True, help_text='Timestamp when the request was approved/rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if the request was rejected', null=True)),
                ('child', models.ForeignKey(help_text='Child for whom the discount is being requested', on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_discount_requests', to='core.child')),
                ('discount', models.ForeignKey(help_text='The discount code being requested to apply', on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='core.discount')),
                ('enrollment', models.ForeignKey(help_text='Enrollment to which the discount should be applied', on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to='core.childenrollment')),
                ('previous_discount', models.ForeignKey(blank=True, help_text='The discount that was on the enrollment before this request (for audit trail)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_requests', to='core.discount')),
            ],
            options={
                'verbose_name': 'Enrollment Discount Request',
                'verbose_name_plural': 'Enrollment Discount Requests',
                'db_table': 'dc_enrollment_discount_request',
                'ordering': ['-requested_date'],
                'indexes': [models.Index(fields=['child', 'status'], name='dc_enrollme_child_i_d54b4a_idx'), models.Index(fields=['enrollment', 'status'], name='dc_enrollme_enrollm_bac0b4_idx'), models.Index(fields=['status', 'requested_date'], name='dc_enrollme_status_fbe46b_idx')],
            },
        ),
    ]
