# Generated by Django 5.0.1 on 2024-01-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_daycare_attendancelog_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='center',
        ),
    ]
