# Generated by Django 5.2.9 on 2026-02-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_enrollment_discount_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_vacation',
            field=models.BooleanField(default=False, help_text='School vacation periods'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='vacation_type',
            field=models.CharField(blank=True, choices=[('ALL', 'All Students'), ('POLYMATH', 'Polymath Students Only'), ('NON_POLYMATH', 'Non-Polymath Students Only')], help_text='Applies only when is_vacation=True', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_other_school_holiday',
            field=models.BooleanField(blank=True, default=False, help_text="DEPRECATED: Use is_vacation=True with vacation_type='NON_POLYMATH' instead", null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_polymath_holiday',
            field=models.BooleanField(blank=True, default=False, help_text="DEPRECATED: Use is_vacation=True with vacation_type='POLYMATH' instead", null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_public_holiday',
            field=models.BooleanField(default=False, help_text='Government/National holidays (e.g., Christmas, New Year)'),
        ),
    ]
