# Generated by Django 5.0.1 on 2024-02-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_attendancelog_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='attendence_type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='In', max_length=30),
        ),
    ]
