# Generated by Django 4.2.15 on 2024-08-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_holidaytype_is_other_school_holiday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaytype',
            name='is_other_school_holiday',
        ),
    ]
