# Generated by Django 5.0.1 on 2026-03-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_holiday_is_vacation_holiday_vacation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoRegenerationRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reason', models.TextField(help_text='Reason for requesting regeneration')),
                ('original_values', models.JSONField(default=dict, help_text='Snapshot of memo values at request time')),
                ('new_calculated_values', models.JSONField(default=dict, help_text='Preview of new calculated values')),
                ('requested_by', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regeneration_requests', to='core.invoicememo')),
            ],
            options={
                'verbose_name': 'Memo Regeneration Request',
                'verbose_name_plural': 'Memo Regeneration Requests',
                'db_table': 'dc_memo_regeneration_request',
                'ordering': ['-requested_at'],
            },
        ),
    ]
