# Generated by Django 5.0.1 on 2024-02-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_attendancelog_attendence_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='attendence_type',
        ),
    ]
