# Generated by Django 4.2.15 on 2024-08-23 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_holidaytype_is_other_school_holiday'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='holiday',
            table='dc_holidays',
        ),
    ]
