# Generated by Django 4.2.15 on 2024-08-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_holiday_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='end_year',
            field=models.CharField(default=2004, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='start_year',
            field=models.CharField(default=2004, max_length=4),
            preserve_default=False,
        ),
    ]
