# Generated by Django 5.0.1 on 2024-02-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_attendancelog_attendence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(default='', upload_to='student_images/', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='child',
            name='qr_code',
            field=models.ImageField(default='', upload_to='student_qr/', verbose_name='img'),
        ),
    ]
