# Generated by Django 5.0.1 on 2024-02-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_child_image_child_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='image',
        ),
        migrations.AddField(
            model_name='child',
            name='child_image',
            field=models.ImageField(default='', upload_to='child_images/'),
        ),
        migrations.AlterField(
            model_name='child',
            name='qr_code',
            field=models.ImageField(default='', upload_to='qr/'),
        ),
    ]
