# Generated by Django 5.0.1 on 2024-08-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_holiday_end_year_holiday_start_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='holiday_type',
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_other_school_holiday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_polymath_holiday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_public_holiday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HolidayType',
        ),
    ]
