# Generated by Django 5.0.1 on 2024-08-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_holiday_holiday_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='no_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
