# Generated by Django 5.0.1 on 2024-08-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_holiday_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='weekdays_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holiday',
            name='weekends_count',
            field=models.IntegerField(default=0),
        ),
    ]
