# Generated by Django 5.0.1 on 2024-08-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_holiday_weekdays_count_holiday_weekends_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='leave_date',
            field=models.DateField(null=True),
        ),
    ]
