# Generated by Django 5.0.1 on 2024-08-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_child_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
