# Generated by Django 5.0.1 on 2024-02-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_child_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='qr_code',
        ),
    ]
