# Generated by Django 5.0.1 on 2024-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_child_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='qr_code',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
