# Generated by Django 5.0.1 on 2024-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_child_admission_date_alter_child_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='resident_contact_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
