# Generated by Django 5.0.1 on 2024-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_child_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_image',
            field=models.ImageField(null=True, upload_to='child_images/'),
        ),
    ]
