# Generated by Django 5.0.1 on 2024-02-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_child_child_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_image',
        ),
    ]
