# Generated by Django 5.0.1 on 2024-06-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_child_child_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'dc_discount', 'verbose_name_plural': 'dc_discounts'},
        ),
        migrations.AlterModelOptions(
            name='ratehistory',
            options={'verbose_name': 'dc_ratehistory', 'verbose_name_plural': 'dc_ratehistory'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'dc_rate', 'verbose_name_plural': 'dc_rates'},
        ),
    ]
