# Generated by Django 5.0.1 on 2024-06-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_discount_options_alter_ratehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'discount', 'verbose_name_plural': 'discounts'},
        ),
        migrations.AlterModelOptions(
            name='ratehistory',
            options={'verbose_name_plural': 'Rate History'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelTable(
            name='ratehistory',
            table='dc_ratehistory',
        ),
    ]
