# Generated by Django 5.0.1 on 2024-06-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_discount_options_alter_ratehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daycare',
            options={'verbose_name': 'center', 'verbose_name_plural': 'centers'},
        ),
        migrations.AlterModelTable(
            name='attendancelog',
            table='dc_attendancelog',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='dc_branch',
        ),
        migrations.AlterModelTable(
            name='child',
            table='dc_child',
        ),
        migrations.AlterModelTable(
            name='childenrollment',
            table='dc_childenrollment',
        ),
        migrations.AlterModelTable(
            name='daycare',
            table='dc_center',
        ),
        migrations.AlterModelTable(
            name='extracharges',
            table='dc_extracharges',
        ),
        migrations.AlterModelTable(
            name='holiday',
            table='dc_holiday',
        ),
        migrations.AlterModelTable(
            name='holidaytype',
            table='dc_holidaytypes',
        ),
        migrations.AlterModelTable(
            name='package',
            table='dc_package',
        ),
    ]
