# Generated by Django 5.0.1 on 2024-06-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_daycare_options_alter_attendancelog_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discount',
            table='dc_discount',
        ),
        migrations.AlterModelTable(
            name='rates',
            table='dc_rate',
        ),
    ]
