# Generated by Django 5.0.1 on 2024-06-12 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_discount_table_alter_rates_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageExtraRates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('extraCharges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracharges')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rates')),
            ],
            options={
                'verbose_name': 'package extra',
                'verbose_name_plural': 'package extras',
                'db_table': 'dc_package_extras',
            },
        ),
    ]
