# Generated by Django 5.0.1 on 2024-06-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_packageextrarates'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageextrarates',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageextrarates',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageextrarates',
            name='package_total',
            field=models.DecimalField(decimal_places=2, default=1521, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packageextrarates',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package'),
        ),
    ]
