# Generated by Django 5.0.1 on 2024-06-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_packageextrarates_base_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_total',
            field=models.DecimalField(decimal_places=2, default=22222, max_digits=8),
            preserve_default=False,
        ),
    ]
