# Generated by Django 5.0.1 on 2024-06-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_package_package_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='no_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='PackageExtraRatesMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('extraCharges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracharges')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
            ],
            options={
                'verbose_name': 'package extra mapping',
                'verbose_name_plural': 'package extras mapping',
                'db_table': 'dc_package_extras_mapping',
            },
        ),
        migrations.DeleteModel(
            name='PackageExtraRates',
        ),
    ]
