# Generated by Django 5.0.1 on 2024-06-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_package_no_hours_alter_package_package_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='base_rate',
        ),
    ]
