# Generated by Django 5.0.1 on 2024-06-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_package_base_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extracharges',
            unique_together={('from_time', 'to_time')},
        ),
        migrations.RemoveField(
            model_name='extracharges',
            name='base_rate',
        ),
    ]
