# Generated by Django 5.0.1 on 2024-06-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_extracharges_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('package_type_name', models.CharField(max_length=550)),
                ('is_holiday_rate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Package Types',
                'db_table': 'dc_package_type',
            },
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype'),
        ),
    ]
