# Generated by Django 5.0.1 on 2024-06-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_packagetype_alter_package_package_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagetype',
            old_name='is_holiday_rate',
            new_name='is_holiday_package',
        ),
    ]
