# Generated by Django 5.0.1 on 2024-06-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_is_holiday_rate_packagetype_is_holiday_package'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extracharges',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='extracharges',
            name='PackageType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rates'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='extracharges',
            unique_together={('from_time', 'to_time', 'PackageType')},
        ),
    ]
