# Generated by Django 5.0.1 on 2024-06-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_extracharges_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracharges',
            old_name='PackageType',
            new_name='package_type',
        ),
        migrations.AlterUniqueTogether(
            name='extracharges',
            unique_together={('from_time', 'to_time', 'package_type')},
        ),
    ]
