# Generated by Django 5.0.1 on 2024-06-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_rename_packagetype_extracharges_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracharges',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype'),
        ),
    ]
