# Generated by Django 5.0.1 on 2024-06-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_extracharges_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraChargesHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('extra_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(null=True)),
                ('extra_charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracharges')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
