# Generated by Django 5.0.1 on 2024-06-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_extrachargeshistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrachargeshistory',
            options={'verbose_name': 'Extra Charge History', 'verbose_name_plural': 'Extra Charge History'},
        ),
        migrations.AlterModelTable(
            name='extrachargeshistory',
            table='dc_extrachargeshistory',
        ),
    ]
