# Generated by Django 5.0.1 on 2024-06-30 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_extrachargeshistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratehistory',
            name='rate',
        ),
        migrations.AlterModelTable(
            name='extracharges',
            table='dc_extrachargeafter530',
        ),
        migrations.CreateModel(
            name='PackageExtraHoursUpTo530',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
            ],
            options={
                'verbose_name': 'extra charges till 5.30',
                'verbose_name_plural': 'extra charges till 5.30',
                'db_table': 'dc_extrachargestill530',
            },
        ),
        migrations.DeleteModel(
            name='PackageExtraRatesMap',
        ),
        migrations.DeleteModel(
            name='RateHistory',
        ),
        migrations.DeleteModel(
            name='Rates',
        ),
    ]
