# Generated by Django 5.0.1 on 2024-07-01 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_ratehistory_rate_alter_extracharges_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageExtraHoursUpTo530',
            new_name='ExtraHoursUpTo530',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_holiday_package',
        ),
        migrations.RenameModel(
            old_name='ExtraCharges',
            new_name='ExtraHoursAfter530',
        ),
        migrations.CreateModel(
            name='PackageExtraHoursAfter530',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extrahoursafter530')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
            ],
            options={
                'verbose_name': 'package mapping extra charges till 5.30',
                'verbose_name_plural': 'extra charges till 5.30',
                'db_table': 'dc_packageextrachargestill530',
            },
        ),
    ]
