# Generated by Django 5.0.1 on 2026-03-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_memo_regeneration_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePriceRevision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_updated', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='The current price at time of revision creation', max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, help_text='The new price to apply', max_digits=12)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, help_text='The percentage change used (optional)', max_digits=6, null=True)),
                ('effective_from', models.DateField(help_text='When the price change takes effect')),
                ('is_applied', models.BooleanField(default=False, help_text='Whether the price has been applied to the package')),
                ('applied_date', models.DateTimeField(blank=True, help_text='When the price was actually applied', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this price revision', null=True)),
                ('fixed_package', models.ForeignKey(blank=True, help_text='The fixed package being updated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_revisions', to='core.fixedpackage')),
                ('flex_package', models.ForeignKey(blank=True, help_text='The flex package being updated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_revisions', to='core.flexpackages')),
            ],
            options={
                'verbose_name': 'Package Price Revision',
                'verbose_name_plural': 'Package Price Revisions',
                'db_table': 'dc_package_price_revisions',
                'ordering': ['-effective_from', '-date_created'],
                'indexes': [models.Index(fields=['effective_from'], name='dc_package__effecti_fe1dd1_idx'), models.Index(fields=['is_applied'], name='dc_package__is_appl_ec0719_idx'), models.Index(fields=['fixed_package', 'effective_from'], name='dc_package__fixed_p_3e9ac4_idx'), models.Index(fields=['flex_package', 'effective_from'], name='dc_package__flex_pa_bd214f_idx')],
            },
        ),
    ]
